### ISSUE TITLE
Additional Info

### ISSUE THREAD

**Issue by CrashNBurns** [ietf-wg-pquip/chosen-algorithms#1]
While not an authoritative source, the latest GSM PQC report contains a good matrix in Section 5 which enumerates the disposition of various countries. 

- https://www.gsma.com/newsroom/wp-content/uploads/PQ.1-Post-Quantum-Telco-Network-Impact-Assessment-Whitepaper-Version1.0.pdf

I wasn't sure how best to preserve this info in a compatible way for this repo, so I hope that sharing the info via an issue is an OK way of sharing with the maintainers.

**Comment by paulehoffman** [comment]
Thanks! However, this list is mostly "intends to" but not "is committed to", and certainly the list is somewhat out of date. Does the GSMA intend to freshen this document (or at least this list) in the future? If so, it would be great to include the parts where there is commitment.

**Comment by CrashNBurns** [comment]
Hey Paul - yes, makes sense (hence the issue instead of a pull request :-)).  I'm not affiliated with GSMA but will certainly keep my eye out for more assertive statements from the various world orgs and come back to help contribute in the future.  Thanks for putting this together and tracking it -- you can close this issue.

**Comment by CrashNBurns** [comment]
Closing
